In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/Data Cleaning1.csv')
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [3]:
# understaning data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [4]:
df.describe()

            Rank       Shows
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000

In [5]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [7]:
df.columns = df.columns.str.replace('\xa0', ' ')
cols = ['Actual gross', 'Adjusted gross (in 2022 dollars)',	'Average gross']
df[cols] = df[cols].apply(lambda x: x.str.replace(r'[\$,]', '', regex=True))

In [8]:
# converting some columns having number, from strings to numerics
cols_to_numerics = ['Peak',	'All Time Peak',	'Actual gross',	'Adjusted gross (in 2022 dollars)',	'Average gross',	'Ref.']
df[cols_to_numerics] = df[cols_to_numerics].apply(pd.to_numeric, errors='coerce')

In [9]:
df['Start_Year'] = df['Year(s)'].str.split('–|-').str[0]

dates = pd.to_numeric(df['Start_Year'], errors='coerce')

In [10]:
# fill the empty places
empty_columns = ['Peak', 'All Time Peak']
df[empty_columns] = df[empty_columns].fillna(df[empty_columns].mean())

In [11]:
df.isnull().sum()

Rank                                 0
Peak                                 0
All Time Peak                        0
Actual gross                         2
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                20
Start_Year                           0
dtype: int64

In [25]:
df = df.drop(columns=['Ref.'])
df['Actual gross'] = df['Actual gross'].fillna(df['Actual gross'].mean())

In [14]:
# checking duplicates
df.duplicated().sum()

np.int64(0)

In [19]:
# checking inconsistencies

cols = ['Artist', 'Tour title']
df[cols] = df[cols].apply(lambda x: x.str.strip().str.lower())

In [20]:
df['Artist'].unique()

array(['taylor swift', 'beyoncé', 'madonna', 'pink', 'celine dion',
       'lady gaga', 'katy perry', 'cher', 'adele'], dtype=object)

In [21]:
df['Tour title'].unique()

array(['the eras tour †', 'renaissance world tour',
       'sticky & sweet tour ‡[4][a]', 'beautiful trauma world tour',
       'reputation stadium tour', 'the mdna tour',
       'taking chances world tour', 'summer carnival †',
       'the formation world tour', 'the 1989 world tour',
       'the mrs. carter show world tour', 'the monster ball tour *',
       'prismatic world tour', 'living proof: the farewell tour ‡[21][a]',
       'confessions tour', 'the truth about love tour',
       'born this way ball', 'rebel heart tour', 'adele live 2016',
       'the red tour'], dtype=object)

In [23]:
pattern = r'\[.*?\]|[†‡*]'

df['Tour title'] = df['Tour title'].str.replace(pattern, '', regex=True).str.strip()

In [29]:
text_cols = ['Artist', 'Tour title']
df[text_cols] = df[text_cols].apply(lambda x: x.str.title())

In [27]:
df.isnull().sum()

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Start_Year                          0
dtype: int64

In [30]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Start_Year
0,1,1.0,2.0,780000000.0,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571,2023
1,2,1.0,2.0,579800000.0,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,2023
2,3,1.0,2.0,411000000.0,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294,2008
3,4,1.0,2.0,397300000.0,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,2018
4,5,1.0,2.0,345675146.0,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,2018