Dealing with strings

In [ ]:
import pandas as pd
import numpy as np

happiness2015 = pd.read_csv('/content/World_Happiness_2015 (1).csv')
happiness2016 = pd.read_csv('/content/World_Happiness_2016.csv')
happiness2017 = pd.read_csv('/content/World_Happiness_2017.csv')
world_dev = pd.read_csv('/content/World_dev.csv')

In [ ]:
world_dev = pd.read_csv("World_dev.csv")
col_renaming = {'SourceOfMostRecentIncomeAndExpenditureData': 'IESurvey'}

merged = pd.merge(left=happiness2015, right=world_dev, how='left',
                 left_on='Country', right_on='ShortName')
merged = merged.rename(col_renaming, axis=1)

In [ ]:
merged[['Country', 'CurrencyUnit']].head()

       Country     CurrencyUnit
0  Switzerland      Swiss franc
1      Iceland    Iceland krona
2      Denmark     Danish krone
3       Norway  Norwegian krone
4       Canada  Canadian dollar

In [ ]:
def extract_last_word(element):
  return str(element).split()[-1]
merged['Currency Apply'] = merged['CurrencyUnit'].apply(extract_last_word)
merged['Currency Apply'].head()

0     franc
1     krona
2     krone
3     krone
4    dollar
Name: Currency Apply, dtype: object

In [ ]:
# using pandas vactorized way
merged['Currency Vectorized'] = merged['CurrencyUnit'].astype(str).str.split().str.get(-1)
merged['Currency Vectorized'].head()

0     franc
1     krona
2     krone
3     krone
4    dollar
Name: Currency Vectorized, dtype: object

In [ ]:
uniques = merged['Currency Vectorized'].unique()
uniques.sort()
uniques

array(['Boliviano', 'Euro', 'Omani', 'afghani', 'ariary', 'baht',
       'balboa', 'birr', 'cedi', 'colon', 'cordoba', 'denar', 'dinar',
       'dirham', 'dollar', 'dong', 'dram', 'forint', 'franc', 'fuerte',
       'gourde', 'guarani', 'hryvnia', 'koruna', 'krona', 'krone', 'kuna',
       'kwacha', 'kwanza', 'kyat', 'lari', 'lek', 'lempira', 'leone',
       'leu', 'lev', 'lilangeni', 'lira', 'loti', 'manat', 'mark',
       'metical', 'naira', 'nan', 'ngultrum', 'ouguiya', 'peso', 'pound',
       'pula', 'quetzal', 'rand', 'real', 'rial', 'riel', 'ringgit',
       'riyal', 'rubel', 'ruble', 'rupee', 'rupiah', 'shekel', 'shilling',
       'sol', 'somoni', 'sterling', 'sum', 'taka', 'tenge', 'tugrik',
       'yen', 'yuan', 'zloty'], dtype=object)

In [ ]:
merged['Currency Vectorized'] = merged['Currency Vectorized'].str.lower()
merged['Currency Vectorized'] = merged['Currency Vectorized'].str.strip()
merged['Currency Vectorized'] = merged['Currency Vectorized'].replace({
    'rubel': 'ruble',
    'rial': 'riyal',
    'sterling': 'pound',
})

In [ ]:
merged['Currency Vectorized'].head()

0     franc
1     krona
2     krone
3     krone
4    dollar
Name: Currency Vectorized, dtype: object

In [ ]:
#working with missing and duplicate data
print(happiness2015.columns.tolist())

['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Standard Error', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']

In [ ]:
happiness2015.columns = happiness2015.columns.str.replace('(', '').str.replace(')', '').str.strip().str.upper()
print(happiness2015.columns.tolist())

['COUNTRY', 'REGION', 'HAPPINESS RANK', 'HAPPINESS SCORE', 'STANDARD ERROR', 'ECONOMY GDP PER CAPITA', 'FAMILY', 'HEALTH LIFE EXPECTANCY', 'FREEDOM', 'TRUST GOVERNMENT CORRUPTION', 'GENEROSITY', 'DYSTOPIA RESIDUAL']

In [ ]:
happiness2016.columns = happiness2016.columns.str.replace('(', '').str.replace(')', '').str.strip().str.upper()
happiness2017.columns = happiness2017.columns.str.replace('(', '').str.replace(')', '').str.strip().str.upper()

combined = pd.concat([happiness2015, happiness2016, happiness2017], ignore_index=True)

In [ ]:
print(combined.notnull().sum().sort_values())

HAPPINESS.SCORE                  155
HAPPINESS.RANK                   155
DYSTOPIA.RESIDUAL                155
TRUST..GOVERNMENT.CORRUPTION.    155
HEALTH..LIFE.EXPECTANCY.         155
ECONOMY..GDP.PER.CAPITA.         155
WHISKER.LOW                      155
WHISKER.HIGH                     155
UPPER CONFIDENCE INTERVAL        157
LOWER CONFIDENCE INTERVAL        157
STANDARD ERROR                   158
TRUST GOVERNMENT CORRUPTION      315
DYSTOPIA RESIDUAL                315
REGION                           315
HAPPINESS SCORE                  315
HAPPINESS RANK                   315
HEALTH LIFE EXPECTANCY           315
ECONOMY GDP PER CAPITA           315
COUNTRY                          470
FAMILY                           470
FREEDOM                          470
GENEROSITY                       470
dtype: int64

In [ ]:
print(f'Columns Before: {len(combined.columns)}')
combined = combined.dropna(thresh=159, axis=1)
print(f'Columns After: {len(combined.columns)}')
print(combined.columns.tolist())

Columns Before: 11
Columns After: 11
['COUNTRY', 'REGION', 'HAPPINESS RANK', 'HAPPINESS SCORE', 'ECONOMY GDP PER CAPITA', 'FAMILY', 'HEALTH LIFE EXPECTANCY', 'FREEDOM', 'TRUST GOVERNMENT CORRUPTION', 'GENEROSITY', 'DYSTOPIA RESIDUAL']

In [ ]:
rows_before = len(combined)
combined = combined.dropna()
print(f"Rows before: {rows_before}")
print(f"Rows after: {len(combined)}")
print(f"Percentage of data lost: {((rows_before - len(combined))/rows_before * 100):.1f}%")

Rows before: 470
Rows after: 315
Percentage of data lost: 33.0%

In [ ]:
# managing duplicates
combined.duplicated().sum()

np.int64(0)