In [ ]:
# importing pandas and numpy libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [ ]:
# loading csv file
district_prices = pd.read_csv('/content/District-prices-monthly.csv')
district_prices.head()

,year_month,district,okrug,secondary_price_per_sqm,newbuild_price_per_sqm,rental_price_per_sqm_monthly,secondary_mom_change_pct,newbuild_mom_change_pct,n_listings_secondary,n_listings_newbuild,n_listings_rental,cbr_key_rate_pct,avg_mortgage_rate_pct
0,2020-01,Arbat,CAO,480000,543700,2000,NaN,NaN,104,68,41,6.00,8.50
1,2020-02,Arbat,CAO,469100,531500,1955,-2.28,-2.24,22,63,50,6.00,8.50
2,2020-03,Arbat,CAO,502200,559800,2093,7.07,5.33,104,56,28,6.00,8.50
3,2020-04,Arbat,CAO,505100,541500,2104,0.56,-3.27,168,29,107,4.25,6.75
4,2020-05,Arbat,CAO,523500,594800,2181,3.65,9.84,66,58,57,4.25,6.75

In [ ]:
# displaying column names
district_prices.columns.tolist()

['year_month',
 'district',
 'okrug',
 'secondary_price_per_sqm',
 'newbuild_price_per_sqm',
 'rental_price_per_sqm_monthly',
 'secondary_mom_change_pct',
 'newbuild_mom_change_pct',
 'n_listings_secondary',
 'n_listings_newbuild',
 'n_listings_rental',
 'cbr_key_rate_pct',
 'avg_mortgage_rate_pct']

In [ ]:
# standarizing column names by replacing - and capatalizing all letters
district_prices.columns = district_prices.columns.str.replace('_', ' ')
district_prices.columns = district_prices.columns.str.upper()

In [ ]:
# displaying columns names after applying changes
district_prices.columns.tolist()

['YEAR MONTH',
 'DISTRICT',
 'OKRUG',
 'SECONDARY PRICE PER SQM',
 'NEWBUILD PRICE PER SQM',
 'RENTAL PRICE PER SQM MONTHLY',
 'SECONDARY MOM CHANGE PCT',
 'NEWBUILD MOM CHANGE PCT',
 'N LISTINGS SECONDARY',
 'N LISTINGS NEWBUILD',
 'N LISTINGS RENTAL',
 'CBR KEY RATE PCT',
 'AVG MORTGAGE RATE PCT']

In [ ]:
# checking for duplicated values
district_prices.duplicated().sum()

np.int64(0)

In [ ]:
# checking for information about columns. which show us datatypes of columns and number of non null values
district_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9804 entries, 0 to 9803
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   YEAR MONTH                    9804 non-null   object
 1   DISTRICT                      9804 non-null   object
 2   OKRUG                         9804 non-null   object
 3   SECONDARY PRICE PER SQM       9804 non-null   int64
 4   NEWBUILD PRICE PER SQM        9804 non-null   int64
 5   RENTAL PRICE PER SQM MONTHLY  9804 non-null   int64
 6   SECONDARY MOM CHANGE PCT      9675 non-null   float64
 7   NEWBUILD MOM CHANGE PCT       9675 non-null   float64
 8   N LISTINGS SECONDARY          9804 non-null   int64
 9   N LISTINGS NEWBUILD           9804 non-null   int64
 10  N LISTINGS RENTAL             9804 non-null   int64
 11  CBR KEY RATE PCT              9804 non-null   float64
 12  AVG MORTGAGE RATE PCT         9804 non-null   float64
dtypes: float64(4), int64(6), object(3)
memory usage: 995.8+ KB

In [ ]:
# we will check missing values
district_prices.isnull().sum()

YEAR MONTH                        0
DISTRICT                          0
OKRUG                             0
SECONDARY PRICE PER SQM           0
NEWBUILD PRICE PER SQM            0
RENTAL PRICE PER SQM MONTHLY      0
SECONDARY MOM CHANGE PCT        129
NEWBUILD MOM CHANGE PCT         129
N LISTINGS SECONDARY              0
N LISTINGS NEWBUILD               0
N LISTINGS RENTAL                 0
CBR KEY RATE PCT                  0
AVG MORTGAGE RATE PCT             0
dtype: int64

As you can see only 2 columns have missing values. We will deal with them when cleaning that particular column. Now we will start with 1st column and then move to next one by one.

In [ ]:
# changing the datatype of 1st column to datetime as the column is representing date
district_prices['YEAR MONTH'] = pd.to_datetime(district_prices['YEAR MONTH'], errors='coerce')

In [ ]:
print(district_prices['YEAR MONTH'].dtype)

datetime64[ns]

In [ ]:
# changing the name of column from YEAR MONTH TO DATE
district_prices.rename(columns= {'YEAR MONTH': 'DATE'}, inplace= True)

In [ ]:
# moving to next column