In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/World_Happiness_2015.csv')
happiness_index_2015 = pd.read_csv('/content/World_Happiness_2015.csv')
happiness_index_2016 = pd.read_csv('/content/World_Happiness_2016.csv')
happiness_index_2017 = pd.read_csv('/content/World_Happiness_2017.csv')
happiness_index_2015['Year'] = 2015
happiness_index_2016['Year'] = 2016
happiness_index_2017['Year'] = 2017
df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [6]:
# Using aggregation to group data and check some facts.
grouped = df.groupby('Region')
happy_grouped = grouped['Happiness Score']
happy_mean = happy_grouped.mean()
print(happy_mean)

Region
Australia and New Zealand          7.285000
Central and Eastern Europe         5.332931
Eastern Asia                       5.626167
Latin America and Caribbean        6.144682
Middle East and Northern Africa    5.406900
North America                      7.273000
Southeastern Asia                  5.317444
Southern Asia                      4.580857
Sub-Saharan Africa                 4.202800
Western Europe                     6.689619
Name: Happiness Score, dtype: float64

In [8]:
happy_median = happy_grouped.median()
print(happy_median)
grouped.count()

Region
Australia and New Zealand          7.285
Central and Eastern Europe         5.286
Eastern Asia                       5.729
Latin America and Caribbean        6.149
Middle East and Northern Africa    5.262
North America                      7.273
Southeastern Asia                  5.360
Southern Asia                      4.565
Sub-Saharan Africa                 4.272
Western Europe                     6.937
Name: Happiness Score, dtype: float64

,Country,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
Region,,,,,,,,,,,
Australia and New Zealand,2,2,2,2,2,2,2,2,2,2,2
Central and Eastern Europe,29,29,29,29,29,29,29,29,29,29,29
Eastern Asia,6,6,6,6,6,6,6,6,6,6,6
Latin America and Caribbean,22,22,22,22,22,22,22,22,22,22,22
Middle East and Northern Africa,20,20,20,20,20,20,20,20,20,20,20
North America,2,2,2,2,2,2,2,2,2,2,2
Southeastern Asia,9,9,9,9,9,9,9,9,9,9,9
Southern Asia,7,7,7,7,7,7,7,7,7,7,7
Sub-Saharan Africa,40,40,40,40,40,40,40,40,40,40,40
Western Europe,21,21,21,21,21,21,21,21,21,21,21

In [17]:
# Combining datasets using CONCAT
data_2015 = happiness_index_2015[['Country',	'Happiness Score', 'Year']].head()
data_2016 = happiness_index_2016[['Country',	'Happiness Score', 'Year']].head()

concating_horizontally = pd.concat([data_2015, data_2016], axis= 1)
print(concating_horizontally)

concating_vertically = pd.concat([data_2015, data_2016], axis= 0)
print(concating_vertically)

       Country  Happiness Score  Year      Country  Happiness Score  Year
0  Switzerland            7.587  2015      Denmark            7.526  2016
1      Iceland            7.561  2015  Switzerland            7.509  2016
2      Denmark            7.527  2015      Iceland            7.501  2016
3       Norway            7.522  2015       Norway            7.498  2016
4       Canada            7.427  2015      Finland            7.413  2016
       Country  Happiness Score  Year
0  Switzerland            7.587  2015
1      Iceland            7.561  2015
2      Denmark            7.527  2015
3       Norway            7.522  2015
4       Canada            7.427  2015
0      Denmark            7.526  2016
1  Switzerland            7.509  2016
2      Iceland            7.501  2016
3       Norway            7.498  2016
4      Finland            7.413  2016

In [19]:
# Combining data sets using MERGE
data_2015_i = happiness_index_2015[['Country',	'Happiness Score', 'Year']].iloc[0:5]
data_2016_ii = happiness_index_2016[['Country',	'Happiness Score', 'Year']].iloc[0:5]

pd.merge(left= data_2015_i, right=data_2016_ii, on= 'Country', suffixes=('_2015', '_2016'))

,Country,Happiness Score_2015,Year_2015,Happiness Score_2016,Year_2016
0,Switzerland,7.587,2015,7.509,2016
1,Iceland,7.561,2015,7.501,2016
2,Denmark,7.527,2015,7.526,2016
3,Norway,7.522,2015,7.498,2016

Transformations in pandas

In [42]:
# simple transformation with series.map
def label(element):
  if element > 1:
    return 'High'
  else:
    return 'Low'

happiness_index_2015['Economy Impact'] = happiness_index_2015['Economy (GDP per Capita)'].map(label)
print(happiness_index_2015[['Country', 'Economy (GDP per Capita)', 'Economy Impact']].iloc[5:11])

        Country  Economy (GDP per Capita) Economy Impact
5       Finland                   1.29025           High
6   Netherlands                   1.32944           High
7        Sweden                   1.33171           High
8   New Zealand                   1.25018           High
9     Australia                   1.33358           High
10       Israel                   1.22857           High

In [43]:
# Using series.apply for flexablility
def label(element, x):
  if element > x:
    return 'High'
  else:
    return 'Low'
happiness_index_2015['Economy Impact'] = happiness_index_2015['Economy (GDP per Capita)'].apply(label, x=0.8)

In [49]:
# analyzing how each column participate in happiness
factors = ['Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']
def percentages(col):
  div = col/happiness_index_2015['Happiness Score']
  return div*100
factors_percentage = happiness_index_2015[factors].apply(percentages)
factors_percentage.head()

,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,18.406617,17.787136,12.408462,8.772506,5.532885,3.911691,33.180177
1,17.224177,18.545563,12.535908,8.315963,1.870784,5.770401,35.736146
2,17.609672,18.075993,11.620035,8.627342,6.424472,4.535539,33.108011
3,19.396437,17.694097,11.768280,8.903616,4.852832,4.613002,32.774661
4,17.857681,17.808132,12.193753,8.522553,4.437458,6.168170,33.011445